CREATE TABLE IF NOT EXISTS salesforce_returns (
    id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    uniqueid text NOT NULL,
    uniqueid_hash varchar(64) NOT NULL,
    trackingtype varchar(100) DEFAULT '',
    sendtype varchar(100) DEFAULT '',
    mid varchar(100) DEFAULT '',
    eid varchar(200) DEFAULT '',
    contactkey varchar(200) DEFAULT '',
    mobilenumber varchar(50) DEFAULT '',
    eventdateutc datetime DEFAULT NULL,
    appid varchar(100) DEFAULT '',
    channelid varchar(100) DEFAULT '',
    channeltype varchar(50) DEFAULT '',
    conversationtype varchar(50) DEFAULT '',
    activityname varchar(150) DEFAULT '',
    channelname varchar(150) DEFAULT '',
    status varchar(100) DEFAULT '',
    reason text,
    jbdefinitionid varchar(200) DEFAULT '',
    sendidentifier varchar(200) DEFAULT '',
    assetid varchar(100) DEFAULT '',
    messagetypeid varchar(100) DEFAULT '',
    operacao__c varchar(100) DEFAULT '',
    cpf_cnpj__c varchar(50) DEFAULT '',
    name varchar(255) DEFAULT '',
    criado_em datetime DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniqueid_hash (uniqueid_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
